# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.

version: "2.3"
services:
  autoware:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:$HOME/Xauthority:rw
      - ~/.gitconfig:$HOME/.gitconfig:rw
      - ../.bashrc:$HOME/.bashrc:rw
      - ~/shared_dir:$HOME/shared_dir:rw
      - ..:$HOME/autoware.ai:rw
    environment:
      - XAUTHORITY=$XAUTH
      - DISPLAY=$DISPLAY
      - USER_ID=1000
    network_mode: host

    # nvidia-docker("runtime" option is available only in v2.3)
    privileged: true
    runtime: nvidia

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
